### ISSUE TITLE
Let's manage our organization - openly and using lessons from other GC github projects

### ISSUE THREAD

**Issue by MaryBethBaker** [canada-ca/welcome#29] opened 2018-04-13 15:33 UTC
Good Morning @Acasovan @smellems @StaceyWilliams!

I started a GitHub management plan in this markdown document: https://github.com/canada-ca/welcome/blob/master/OrganizationMangagementPlan.md

I was hoping that if you have information from other sources or know of practices we should adopt for managing our Canada-ca organization you can either log them as issues or edit the markdown directly. My intention is to develop the document, get it translated and then get feedback from the community.

Thanks,
Mary Beth

**Comment by MaryBethBaker** [comment] 2018-04-13 15:33
// @laurawesley

**Comment by patcon** [comment] 2018-04-13 17:30
Also, discussion of project templates would be rad. Templates can help guide certain behaviours when project are spinning up, and allows people running existing projects to share know-how back into the templates, where others can "learn" without a direct conversation.

https://github.com/audreyr/cookiecutter

Templates are being more useful now that GitHub workflows themselves can be automated via [Probot](https://probot.github.io/) plugins. These allow automation in the GitHub issues, and in the setting of files. For example, a template could guide a new project toward using [protected branches](https://help.github.com/articles/about-protected-branches/) with everything pre-configured via the probot's [settings plugin](https://probot.github.io/apps/settings/). With the `master` branch fully protected so only project leads can push to it, then push access on the rest of the repo can be shared more liberally, and this generosity of responsibility can change the shape of the community that grows around the project by giving contributors (inside and outside gov), more ownership! :)

Or we use the template, with config for pre-creating some github issue labels, so that we guide new projects toward using tried-and-true patterns there -- like ["first-timers-only"](https://blog.kentcdodds.com/first-timers-only-78281ea47455), and submitting their projects to http://up-for-grabs.net/, where lots of coding bootcamps send their new students to practice :)

Anyhow, there's lots of opportunity here. Excited for this conversation even if templates are out of scope!

**Comment by patcon** [comment] 2018-04-13 21:33
Re-organized some of my comments above to be more point form and digestible (hopefully!) :)

**Comment by patcon** [comment] 2018-04-13 21:42
1. ❤️ I feel inspired by the Hoodie project, and eagerly anticipate a world where the Government of Canada presences online can be just as welcoming of newcomers :)
    - [`hoodiehq` GitHub organization](https://github.com/hoodiehq)
    - Hoodie's [Community page](http://hood.ie/community/) is a great place to click around

**Comment by pjackson28** [comment] 2018-05-25 19:33
Looking at the repo permissions assigned to Canada-ca members‎ by default, they are granted write access to all Canada-ca repos. This means that they can make changes to any Canada-ca repo without restriction, including merging in any pull request, pushing changes directly to the main repo (without a pull request) or even rewriting/corrupting the whole history for a repo.

Normally projects hand out write access sparingly (normally to maintainers) because of the large potential for damage that could be caused. For instance the WET repo was completely wiped out twice by people with write access (accidental both times). Fortunately we were able to restore from a recent fork each time but it still took nearly a day to fully recover.

Since there are a lot of members (63 at last count) with varying levels of skill and comfort with Git/GitHub, I recommend taking a much safer approach where the default organization permissions are set to “Read”. After that, each repo owner would set up teams with admin and write privileges to restore admin and write access to those who actually need it (adding/removing members as needed). This would give more control to each repo owner and would greatly reduce the risk of problems (e.g., a minor contributor merging in something that breaks the build for everyone).

**Comment by chrismajewski** [comment] 2018-05-25 20:00
@pjackson28 agreed

We should likely disable:
* Repository deletion (self explanatory)
* Repository visibility change (hiding public conversation)
* Repository forking (private repos should stay private)

Change:
* Organization members from write to read (as per Paul's recommendation)

I don't mind allowing Repository creation, improper behavior costs you the access with a paper trail explaining what happened.

We also have a large owner count, it's hard to gain consensus on those recommended changes to apply them.  Any issues with the proposal?  Do we apply this time next week barring issue?

@gcharest @laurawesley @markwooff @MaryBethBaker @pjackson28 @RachelMuston @sboots @sdkibb @smellems @steve-h @thomasgohard

**Comment by gcharest** [comment] 2018-05-25 20:34
Agreed, an Integration-Manager Workflow should probably be established. Recommending the least amount of friction for contribution as possible to avoid (gulp) bureaucratic burden...

Also, we probably want to keep in mind that GitHub isn't the only service provider.

**Comment by gcharest** [comment] 2018-05-25 20:34
Also, training...

**Comment by nschonni** [comment] 2018-05-25 20:55
> For instance the WET repo was completely wiped out twice by people with write access (accidental both times)

*tips hat*

___

The subteam concept makes it much easier to organize those permissions now. EX:
- Digital Playbook (Default root team for people working on the repo(s). Read access for assignment and labelling issues)
  - [Digital Playbook Admin](https://github.com/orgs/canada-ca/teams/digital-playbook-admins_ (for the repo admins)
  - [Digital Playbook Contibutors](https://github.com/orgs/canada-ca/teams/digital-playbook-reviewers/teams) (for Write access) 
    - Digital playbook Subject Matter X

With the subteams, you only see the root team when you look at https://github.com/orgs/canada-ca/teams

**Comment by sdkibb** [comment] 2018-05-25 21:18
@gcharest Github isn't the only service provider like Facebook isn't the only place to promote your dept/brand/messaging but we still don't use MySpace.

 It's Github or nothing IMO. If we get bogged down with a discussion on what's the best place to openly share code we'll be distracting from the goal. It shouldn't even be a line item.

**Comment by gcharest** [comment] 2018-05-25 21:34
Hi @sdkibb,

Thanks for sharing your opinion as well. I'm not suggesting that we debate which service provider to choose. I would rather each team be free to use whatever one suits their needs. I was just hinting that whatever we come up could be leveraged for others as well.

**Comment by laurawesley** [comment] 2018-05-25 23:05
Yes totally agree with @pjackson28 and @chrismajewski. Let’s do it! We just started this with the least amount of friction as possible to see what emerged. It makes sense to make it a bit of a safer space to operate at this point. 

Thanks for starting this valuable convo @MaryBethBaker!

I’m very interested in @patcon ‘s idea of having citizen involvement...although I’m not sure we are doing anything to prevent that now. Maybe we just need to do more to encourage it. Also want to encourage inter-jurisdictional collaboration. 

Now thinking @nschonni was the one who ‘accidentally’ blew away the repos hahahaha 🤪

**Comment by MaryBethBaker** [comment] 2018-05-25 23:56
My only caveat is that we don’t have any to manage a system if we change the permissions and more time is required to grant/update/remove permissions.



On May 25, 2018, at 7:05 PM, Laura Wesley <notifications@github.com<mailto:notifications@github.com>> wrote:


Yes totally agree with @pjackson28<https://github.com/pjackson28> and @chrismajewski<https://github.com/chrismajewski>. Let’s do it! We just started this with the least amount of friction as possible to see what emerged. It makes sense to make it a bit of a safer space to operate at this point.

Thanks for starting this valuable convo @MaryBethBaker<https://github.com/MaryBethBaker>!

I’m very interested in @patcon<https://github.com/patcon> ‘s idea of having citizen involvement...although I’m not sure we are doing anything to prevent that now. Maybe we just need to do more to encourage it. Also want to encourage inter-jurisdictional collaboration.

Now thinking @nschonni<https://github.com/nschonni> was the one who ‘accidentally’ blew away the repos hahahaha 🤪

**Comment by pjackson28** [comment] 2018-05-26 00:01
It was memorable but he wasn't the only one to do it. We also had someone else who was new to GitHub who was trying a few experiments and knocked out the main WET repo in the middle of a 10+ department codesprint for building WET4 and the Canada.ca theme (oops!).

So to avoid that on our repo, we turned on branch protection for the master branch which prevents force pushes to that branch (main culprit for wiping out repos) as well as deleting that branch (can tell protection is on by the shield lock icon for that branch). Suggest that everyone do that for your respective repos as well so you don't repeat that unfortunate part of WET's history. You can do that by going to Settings / Branches and enabling Branch protection rules for master.

**Comment by nschonni** [comment] 2018-05-26 00:32
> My only caveat is that we don’t have any to manage a system if we change the permissions and more time is required to grant/update/remove permissions.

It seems like whoever is the admin on the team (rather than the org admin) can add other members to the team https://developer.github.com/v3/teams/members/#add-or-update-team-membership

**Comment by pjackson28** [comment] 2018-05-26 01:04
I can confirm that the org admin isn't needed for managing teams (adding/removing members and changing permissions). Before I was changed into an owner, all I needed help with from org owners was adding people to the Canada-ca organization (thanks to @smellems for patiently dealing with all my add member requests).

So as long as people are already members of the Canada-ca org, then there work for the org admin in managing teams, only for the repo maintainers (and even then it isn't much work).

**Comment by gcharest** [comment] 2018-05-31 19:51
Also was just brought to my attention: Official languages

Il serait probablement utile de mettre en place une bonne stratégie pour gérer le contenu dans les deux langues. (Excellent travail sur le [guide numérique](https://canada-ca.github.io/digital-playbook-guide-numerique/en/overview.html) @pjackson28

**Comment by gcharest** [comment] 2018-06-01 00:08
Just noticed that section two of the [Organization Management Plan](https://github.com/canada-ca/welcome/blob/master/OrganizationMangagementPlan.md) addresses Bilingualism.

**Comment by gcharest** [comment] 2018-06-01 00:29
@ptd-tbs Thanks for sharing! I like how 6 and 9 have the same title :) (different angle, though).

**Comment by chrismajewski** [comment] 2018-06-07 12:12
MB and I got to debating the check boxes yesterday and I forgot to change the initial request.

In lieu of a formal management structure/plan we collected agreement by thumbs and silence.  I'll change it now and keep an eye for complaints.  If an owner needs help resolving a permission issue in a repository feel free to @ me for help.

**Comment by gcharest** [comment] 2018-06-07 12:19
Hi Chris! Happy to make the changes myself, just didn't see any subsequent
discussion here 😉.

Thanks

**Comment by gcharest** [comment] 2018-06-07 12:29
@chrismajewski Awesome, thanks for the change. Let's chat if you have a minute today!

**Comment by nschonni** [comment] 2018-06-07 19:23
Ran into this over with the Digital Playbook https://github.community/t5/How-to-use-Git-and-GitHub/CODEOWNERS-works-with-users-but-not-teams/m-p/4991#M1612
The CODEOWNERS only works if the group you are using has Write access.

**Comment by thomasgohard** [comment] 2018-10-17 16:01
Adding another management topic: Approving third-party apps.

We should have criteria to use to determine whether to accept or deny third-party apps requested by members of the organisation. Not sure what's appropriate, but probably something about the level of access requested by the third-party app combine with the trustworthiness of the developer behind the app.

Thoughts?

**Comment by gcharest** [comment] 2018-10-17 16:34
That's a very good point...

Le mer. 17 oct. 2018 à 12:01, Thomas Gohard <notifications@github.com> a
écrit :

**Comment by gcharest** [comment] 2018-10-19 12:36
I think we may need a more thorough vetting of 3rd party apps accessing our
organisation in GitHub. Might just be me being overly cautious 😉

Le ven. 19 oct. 2018 02 h 24, Patrick Connolly <notifications@github.com> a
écrit :

**Comment by thomasgohard** [comment] 2018-10-26 19:46
I guess the first criterion should probably be that the app is free. Unless someone wants to volunteer their credit card...

It's not clear what kind of vetting/auditing GitHub does before putting an app on their Marketplace, but that the app is on the GitHub Marketplace could be another criterion to judge the trustworthiness of the app.

**Comment by gcharest** [comment] 2018-10-27 12:49
@thomasgohard I agree cost is one factor to consider. 

The other is how policies and guidance about third party applications work (I need to reread those). GitHub is just one instance where 3rd party apps are available on a SaaS. What's the process in these general cases? Like apps for Google Suites or other platforms?

**Comment by gcharest** [comment] 2019-05-01 19:38
So, long time no news!

This is to inform everyone that we will be shortly activating [2FA](https://help.github.com/en/articles/securing-your-account-with-two-factor-authentication-2fa) on the organization. So, I'll list everyone that has set their profile as public here and for everyone else, well, you'll be kicked out if 2FA is not activated. The problem is that there's no way to directly connect with you via GitHub so... yeah.

@chrismajewski @laurawesley @MaryBethBaker @patlaj @PatLittle @pjackson28 @smellems @thomasgohard @wendyliao2018 

If your teammates are not listed above but you know they're using the Canada-ca repos and they need member rights, please contact me @ guillaume.charest@tbs-sct.gc.ca

Also, only GC employees will continue to have the right to be a member of the organisation. For external collaborators, then can be invited as... Outside collaborators. 

Thanks!

**Comment by MaryBethBaker** [comment] 2020-07-09 12:46
Hoping to archive this issue. Cc @ShadeWyrm

**Comment by ShadeWyrm** [comment] 2020-07-10 12:08
Closing. It's been long enough since 2FA was enabled that this notice can come down. :)

**Closed by ShadeWyrm** 2020-07-10 12:08 UTC
